# Generated by Django 4.0.4 on 2022-05-10 14:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='rsj_company',
            fields=[
                ('company_reg_no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('discount_rate', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(1.0)])),
            ],
            options={
                'db_table': 'rsj_company',
            },
        ),
        migrations.CreateModel(
            name='rsj_customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('pincode', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(regex='^[0-9]{5}$')])),
                ('phone_no', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^[0-9]{10}$')])),
                ('email', models.EmailField(max_length=150)),
                ('dr_lno', models.CharField(max_length=19, validators=[django.core.validators.RegexValidator(regex='^[A-Za-z0-9]{19}$')])),
                ('customer_type', models.CharField(choices=[('I', 'Individual'), ('C', 'Corporate')], default='I', max_length=1)),
                ('username', models.OneToOneField(db_column='username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rsj_customer',
            },
        ),
        migrations.CreateModel(
            name='rsj_discount',
            fields=[
                ('coupon_code', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(regex='^[A-Za-z0-9]{5,10}$')])),
                ('rate', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(1.0)])),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'rsj_discount',
            },
        ),
        migrations.CreateModel(
            name='rsj_invoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('invoice_date', models.DateTimeField(auto_now_add=True)),
                ('pendng_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
            ],
            options={
                'db_table': 'rsj_invoice',
            },
        ),
        migrations.CreateModel(
            name='rsj_location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('pincode', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(regex='^[0-9]{5}$')])),
                ('phone_no', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^[0-9]{10}$')])),
            ],
            options={
                'db_table': 'rsj_location',
            },
        ),
        migrations.CreateModel(
            name='rsj_plan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('cost', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'rsj_plan',
            },
        ),
        migrations.CreateModel(
            name='rsj_vehicle_class',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('rate_per_day', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1.0)])),
                ('over_mileage_fee', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1.0)])),
                ('daily_limit', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(1.0)])),
            ],
            options={
                'db_table': 'rsj_vehicle_class',
            },
        ),
        migrations.CreateModel(
            name='rsj_vehicle',
            fields=[
                ('vin', models.CharField(max_length=17, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(regex='^[A-Za-z0-9]{17}$')])),
                ('make', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('year', models.IntegerField(validators=[django.core.validators.RegexValidator(regex='^[1-9][0-9]{3}$')])),
                ('availability', models.BooleanField(default=True)),
                ('lpn', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(regex='^[A-Za-z0-9]{6,7}$')])),
                ('class_id', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, to='rental.rsj_vehicle_class')),
                ('location_id', models.ForeignKey(db_column='location_id', on_delete=django.db.models.deletion.CASCADE, to='rental.rsj_location')),
            ],
            options={
                'db_table': 'rsj_vehicle',
            },
        ),
        migrations.CreateModel(
            name='rsj_service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('odometer_start', models.IntegerField()),
                ('odometer_end', models.IntegerField(blank=True, null=True)),
                ('coupon_code', models.ForeignKey(db_column='coupon_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rental.rsj_discount')),
                ('customer_id', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.RESTRICT, to='rental.rsj_customer')),
                ('end_location_id', models.ForeignKey(db_column='end_location_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='end', to='rental.rsj_location')),
                ('service_type', models.ForeignKey(db_column='service_type', on_delete=django.db.models.deletion.DO_NOTHING, to='rental.rsj_plan')),
                ('start_location', models.ForeignKey(db_column='start_location', on_delete=django.db.models.deletion.DO_NOTHING, related_name='start', to='rental.rsj_location')),
                ('vin', models.ForeignKey(db_column='vin', on_delete=django.db.models.deletion.RESTRICT, to='rental.rsj_vehicle')),
            ],
            options={
                'db_table': 'rsj_service',
            },
        ),
        migrations.CreateModel(
            name='rsj_payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('method', models.CharField(max_length=4)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('date', models.DateTimeField(db_column='DATE')),
                ('card_no', models.CharField(max_length=16, null=True, validators=[django.core.validators.RegexValidator(regex='^[0-9]{16}$')])),
                ('name_on_card', models.CharField(max_length=30, null=True)),
                ('exp_date', models.DateTimeField(null=True)),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rental.rsj_invoice')),
            ],
            options={
                'db_table': 'rsj_payment',
            },
        ),
        migrations.AddField(
            model_name='rsj_invoice',
            name='service_id',
            field=models.ForeignKey(db_column='service_id', on_delete=django.db.models.deletion.DO_NOTHING, to='rental.rsj_service'),
        ),
        migrations.CreateModel(
            name='rsj_ind_cst',
            fields=[
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='rental.rsj_customer')),
                ('policy_no', models.CharField(max_length=13)),
                ('insurance_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'rsj_ind_cst',
                'unique_together': {('customer', 'policy_no')},
            },
        ),
        migrations.CreateModel(
            name='rsj_corp_cst',
            fields=[
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='rental.rsj_customer')),
                ('emp_id', models.CharField(max_length=10)),
                ('reg_no', models.ForeignKey(db_column='reg_no', on_delete=django.db.models.deletion.DO_NOTHING, to='rental.rsj_company')),
            ],
            options={
                'db_table': 'rsj_corp_cst',
            },
        ),
    ]
