# Generated by Django 4.0.4 on 2022-05-09 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='rsj_customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=1)),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('zipcode', models.CharField(max_length=5)),
                ('state', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('phone_no', models.BigIntegerField()),
                ('dr_lno', models.CharField(max_length=19)),
                ('username', models.OneToOneField(db_column='username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rsj_customer',
            },
        ),
        migrations.CreateModel(
            name='rsj_invoice',
            fields=[
                ('invoice_id', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('invoice_date', models.DateTimeField(auto_now_add=True)),
                ('pendng_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
            ],
            options={
                'db_table': 'rsj_invoice',
            },
        ),
        migrations.CreateModel(
            name='rsj_payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('method', models.CharField(max_length=4)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('date', models.DateTimeField(db_column='DATE')),
                ('card_no', models.BigIntegerField()),
                ('name_on_card', models.CharField(max_length=30)),
                ('exp_date', models.DateTimeField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rental.rsj_invoice')),
            ],
            options={
                'db_table': 'rsj_payment',
            },
        ),
        migrations.CreateModel(
            name='rsj_service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('odometer_start', models.IntegerField()),
                ('odometer_end', models.IntegerField(blank=True, null=True)),
                ('coupon_code', models.ForeignKey(db_column='coupon_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rental.rsj_discount')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rental.rsj_customer')),
                ('end_location_id', models.ForeignKey(db_column='end_location_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_e_location', to='rental.rsj_location')),
                ('service_type', models.ForeignKey(db_column='service_type', on_delete=django.db.models.deletion.DO_NOTHING, to='rental.rsj_plan')),
                ('start_location', models.ForeignKey(db_column='start_location', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_s_location', to='rental.rsj_location')),
                ('vin', models.ForeignKey(db_column='vin', on_delete=django.db.models.deletion.DO_NOTHING, to='rental.rsj_vehicle')),
            ],
            options={
                'db_table': 'rsj_service',
            },
        ),
        migrations.RemoveField(
            model_name='rsjcorpcst',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='rsjindcst',
            name='customer',
        ),
        migrations.DeleteModel(
            name='RsjInvoice',
        ),
        migrations.DeleteModel(
            name='RsjPayment',
        ),
        migrations.DeleteModel(
            name='RsjService',
        ),
        migrations.CreateModel(
            name='rsj_corp_cst',
            fields=[
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='rental.rsj_customer')),
                ('emp_id', models.CharField(max_length=10)),
                ('reg_no', models.ForeignKey(db_column='reg_no', on_delete=django.db.models.deletion.DO_NOTHING, to='rental.rsj_company')),
            ],
            options={
                'db_table': 'rsj_corp_cst',
            },
        ),
        migrations.CreateModel(
            name='rsj_ind_cst',
            fields=[
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='rental.rsj_customer')),
                ('policy_no', models.CharField(max_length=13)),
                ('insurance_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'rsj_ind_cst',
                'unique_together': {('customer', 'policy_no')},
            },
        ),
        migrations.DeleteModel(
            name='RsjCorpCst',
        ),
        migrations.DeleteModel(
            name='RsjCustomer',
        ),
        migrations.DeleteModel(
            name='RsjIndCst',
        ),
        migrations.AddField(
            model_name='rsj_invoice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rental.rsj_service'),
        ),
    ]
