permission = [

'add_rsj_company',
'change_rsj_company',
'delete_rsj_company',
'view_rsj_company',

'add_rsj_customer',
'change_rsj_customer',
'delete_rsj_customer',
'view_rsj_customer',

'add_rsj_discount',
'change_rsj_discount',
'delete_rsj_discount',
'view_rsj_discount',

'add_rsj_invoice',
'delete_rsj_invoice',
'view_rsj_invoice',

'add_rsj_location',
'change_rsj_location',
'delete_rsj_location',
'view_rsj_location',

'add_rsj_plan',
'change_rsj_plan',
'delete_rsj_plan',
'view_rsj_plan',

'add_rsj_vehicle_class',
'change_rsj_vehicle_class',
'delete_rsj_vehicle_class',
'view_rsj_vehicle_class',

'add_rsj_ind_cust',
'change_rsj_ind_cust',
'delete_rsj_ind_cust',
'view_rsj_ind_cust',

'add_rsj_vehicle',
'change_rsj_vehicle',
'delete_rsj_vehicle',
'view_rsj_vehicle',
'add_rsj_service',
'change_rsj_service',
'delete_rsj_service',
'view_rsj_service',
'add_rsj_payment',
'change_rsj_payment',
'delete_rsj_payment',
'view_rsj_payment',
'add_user',
'change_user',
'delete_user',
'view_user',
'add_rsj_corp_cust',
'change_rsj_corp_cust',
'delete_rsj_corp_cust',
'view_rsj_corp_cust',

]


employee_permission = [

'add_rsj_company',
'change_rsj_company',
'delete_rsj_company',
'view_rsj_company',

'add_rsj_customer',
'change_rsj_customer',
'delete_rsj_customer',
'view_rsj_customer',

'add_rsj_discount',
'change_rsj_discount',
'delete_rsj_discount',
'view_rsj_discount',

'add_rsj_invoice',
'delete_rsj_invoice',
'view_rsj_invoice',

'add_rsj_location',
'change_rsj_location',
'delete_rsj_location',
'view_rsj_location',

'add_rsj_plan',
'change_rsj_plan',
'delete_rsj_plan',
'view_rsj_plan',

'add_rsj_vehicle_class',
'change_rsj_vehicle_class',
'delete_rsj_vehicle_class',
'view_rsj_vehicle_class',

'add_rsj_ind_cust',
'change_rsj_ind_cust',
'delete_rsj_ind_cust',
'view_rsj_ind_cust',

'add_rsj_vehicle',
'change_rsj_vehicle',
'delete_rsj_vehicle',
'view_rsj_vehicle',

'add_rsj_service',
'change_rsj_service',
'delete_rsj_service',
'view_rsj_service',

'add_rsj_payment',
'change_rsj_payment',
'delete_rsj_payment',
'view_rsj_payment',

'add_user',
'change_user',
'delete_user',
'view_user',

'add_rsj_corp_cust',
'change_rsj_corp_cust',
'delete_rsj_corp_cust',
'view_rsj_corp_cust',
]

permission = [
'add_logentry',
'change_logentry',
'delete_logentry',
'view_logentry',
'add_permission',
'change_permission',
'delete_permission',
'view_permission',
'add_group',
'change_group',
'delete_group',
'view_group',
'add_contenttype',
'change_contenttype',
'delete_contenttype',
'view_contenttype',
'add_session',
'change_session',
'delete_session',
'view_session',
'add_rsj_company',
'change_rsj_company',
'delete_rsj_company',
'view_rsj_company',
'add_rsj_customer',
'change_rsj_customer',
'delete_rsj_customer',
'view_rsj_customer',
'add_rsj_discount',
'change_rsj_discount',
'delete_rsj_discount',
'view_rsj_discount',
'add_rsj_invoice',
'change_rsj_invoice',
'delete_rsj_invoice',
'view_rsj_invoice',
'add_rsj_location',
'change_rsj_location',
'delete_rsj_location',
'view_rsj_location',
'add_rsj_plan',
'change_rsj_plan',
'delete_rsj_plan',
'view_rsj_plan',
'add_rsj_vehicle_class',
'change_rsj_vehicle_class',
'delete_rsj_vehicle_class',
'view_rsj_vehicle_class',
'add_rsj_ind_cust',
'change_rsj_ind_cust',
'delete_rsj_ind_cust',
'view_rsj_ind_cust',
'add_rsj_vehicle',
'change_rsj_vehicle',
'delete_rsj_vehicle',
'view_rsj_vehicle',
'add_rsj_service',
'change_rsj_service',
'delete_rsj_service',
'view_rsj_service',
'add_rsj_payment',
'change_rsj_payment',
'delete_rsj_payment',
'view_rsj_payment',
'add_user',
'change_user',
'delete_user',
'view_user',
'add_rsj_corp_cust',
'change_rsj_corp_cust',
'delete_rsj_corp_cust',
'view_rsj_corp_cust',

]


customer_permission = [

'view_rsj_company',
'change_rsj_customer',
'view_rsj_customer',
'view_rsj_discount',
'view_rsj_invoice',

'view_rsj_location',

'view_rsj_plan',

'view_rsj_vehicle_class',

'add_rsj_ind_cust',
'change_rsj_ind_cust',
'view_rsj_ind_cust',

'view_rsj_vehicle',

'add_rsj_service',
'change_rsj_service',
'delete_rsj_service',
'view_rsj_service',

'add_rsj_payment',
'change_rsj_payment',
'delete_rsj_payment',
'view_rsj_payment',

'add_rsj_corp_cust',
'change_rsj_corp_cust',
'view_rsj_corp_cust',
]